### ISSUE TITLE
Dependencies from multiple repositories

### ISSUE THREAD

**Issue by Nalsai** [flatpak/flatpak-github-actions#104]
I'm trying to build an extension for an app in my personal repository. For that the app needs to be installed from that repository. However I also need the rust extension for the freedesktop sdk from flathub. As only one repository to install dependencies from can be specified, there is always one missing.

My idea to solve this would be to allow running a custom script before the build, in which I could install the required app from my repository.

**Comment by Nalsai** [comment]
I'm not that experienced with github actions. I think it might be already possible to do that, I just don't know how to. So maybe some documentation would be good.

**Comment by andyholmes** [comment]
After the `actions/checkout` step should be fine:

```yml
   <snip>

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Steps that use "run" here are executed in a Fedora container
    - name: Install extra dependencies
      run: |
        flatpak remote-add --if-not-exists foobar https://foobar.baz/repo/index.flatpakrepo
        flatpak install foo.bar.Baz -y
```
