### ISSUE TITLE
Error CI/CD: Cannot change ownership

### ISSUE THREAD

**Issue by lyskouski** [flatpak/flatpak-github-actions#172]
Hello,

Error is reproduced for both v5 and v6 versions. Nothing was changed in the context of a Linux Flathub distribution.

![image](https://github.com/flatpak/flatpak-github-actions/assets/8281925/0a33217e-8714-4234-9af8-e66f6bafa016)

https://github.com/lyskouski/app-finance/actions/runs/7198767614/job/19609849475
```
 Committing stage build-zenity to cache
========================================================================
Building module Fingrom in /__w/app-finance/app-finance/.flatpak-builder/build/Fingrom-1
========================================================================
Running: mkdir -p Fingrom
Running: tar -xf fingrom_Linux.tar.gz -C Fingrom
tar: com.tercad.fingrom.desktop: Cannot change ownership to uid 1001, gid 127: Invalid argument
```
Used script:
```yaml
  build-flatpak:
    name: Create Linux Flatpak build
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-45
      options: --privileged
    steps:
      - uses: actions/checkout@v3

// ... other steps

      - name: Build Linux Flatpak
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: fingrom_LinuxFlatpak.flatpak
          manifest-path: linux-flatpak/com.tercad.fingrom.yml
```

Flathub build: https://github.com/flathub/com.tercad.fingrom/pull/8

Would rely on your assistance. Thanks in advance
