### ISSUE TITLE
Builder fails installing Gnome/47 SDK; Seemingly missing double slash character

### ISSUE THREAD

**Issue by ndom91** [flatpak/flatpak-github-actions#206]
I'm trying to build my flatpak with `flatpak/flatpak-github-actions/flatpak-builder@v6` and it is failing in this GHA job:
```yaml
- name: Flatpak build
  uses: flatpak/flatpak-github-actions/flatpak-builder@v6
  with:
    bundle: com.gitbutler.app.flatpak
    manifest-path: crates/gitbutler-tauri/flatpak/manifest.flatpak.yml
    cache-key: flatpak-builder-${{ github.sha }}
    arch: ${{ matrix.arch }}
```

With the following error message:

```
Installing org.gnome.Sdk/47 from flathub
error: Nothing matches org.gnome.Sdk in remote flathub
Error installing deps: running `flatpak --system install -y --noninteractive flathub org.gnome.Sdk/47`: Child process exited with code 1
```

Specifically when trying to install the Gnome 47 SDK:

```
flatpak --system install -y --noninteractive flathub org.gnome.Sdk/47
```

Runnign this locally also does not work, it seems that the slash needs to be doubled up, i.e.

```
flatpak --system install -y --noninteractive flathub org.gnome.Sdk//47
```

**Comment by ndom91** [comment]
If I try to manually install it via

```
flatpak --system install -y --noninteractive flathub org.gnome.Sdk//47
```

It still attempts to run the broken command :/ 

![image](https://github.com/user-attachments/assets/0eee313b-6d59-483b-8cce-2d03cd4f40cd)

**Comment by ndom91** [comment]
Same is true with `flatpak/flatpak-github-actions/flatpak-builder@master` usingi this step:

```
- name: Flatpak build
  uses: flatpak/flatpak-github-actions/flatpak-builder@master
  with:
    bundle: com.gitbutler.app.flatpak
    manifest-path: crates/gitbutler-tauri/flatpak/manifest.flatpak.yml
    cache-key: flatpak-builder-${{ github.sha }}
    arch: ${{ matrix.arch }}
```
