### ISSUE TITLE
SDK extensions not installing?

### ISSUE THREAD

**Issue by jcm93** [flatpak/flatpak-github-actions#220]
I'm in the preliminary stages of experimenting with upstreaming the Flatpak build process for a project, and I'm running into some issues/confusion.

The application has a Rust dependency that we need to build and package inside the bundle.

At the top of my manifest file, I've declared the Rust extension:

```yml
app-id: dev.ares.ares
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.rust-stable:
    version: '24.08'
    remove-after-build: true
```

The Rust module we need to build is declared first:

```yml
modules:
  - name: librashader
    buildsystem: simple
    build-options:
      append-path: /usr/lib/sdk/rust-stable/bin
      env:
        CARGO_HOME: /run/build/librashader/cargo
    build-commands:
      - rustup --version # added for debugging purposes
      - cargo run -p librashader-build-script -- --profile optimized --stable
```

In the GitHub Actions build log, I'm not seeing any evidence of our extension being installed:

```
Building the flatpak...
/usr/bin/xvfb-run --auto-servernum flatpak-builder --repo=repo --disable-rofiles-fuse --install-deps-from=flathub --force-clean --default-branch=master --arch=x86_64 --ccache flatpak_app /__w/ares/ares/ares/packaging/flatpak-github-action-modified-dev.ares.ares.yaml
Dependency Sdk: org.freedesktop.Sdk 24.08
Updating org.freedesktop.Sdk/x86_64/24.08
Updating runtime/org.freedesktop.Platform.GL.default/x86_64/24.08
Updating runtime/org.freedesktop.Platform.GL.default/x86_64/24.08extra
Installing runtime/org.freedesktop.Platform.openh264/x86_64/2.5.1
Updating runtime/org.freedesktop.Sdk.Locale/x86_64/24.08
Updating runtime/org.freedesktop.Sdk/x86_64/24.08
Dependency Runtime: org.freedesktop.Platform 24.08
Updating org.freedesktop.Platform/x86_64/24.08
Updating runtime/org.freedesktop.Platform.Locale/x86_64/24.08
Updating runtime/org.freedesktop.Platform/x86_64/24.08
Downloading sources
...
```

Then when it comes time to actually execute our build commands, Rust definitely doesn't seem to be installed:

```
Starting build of dev.ares.ares
========================================================================
Building module librashader in /__w/ares/ares/.flatpak-builder/build/librashader-1
========================================================================
Running: rustup --version
/bin/sh: line 1: rustup: command not found
Error: module librashader: Child process exited with code 127
```

Do I need a separate GitHub Actions step to install Rust in this instance? I thought that that would be performed by the Flatpak builder? I've inspected the test Rust application in this repository, but it doesn't seem like it has to do any extra hooplah to make the container on CI aware of Rust's existence.

Complete details:
Build log: https://github.com/jcm93/ares/actions/runs/14173778976/job/39703615634
Manifest: https://github.com/jcm93/ares/blob/flatpak/packaging/dev.ares.ares.yaml
CI flow: https://github.com/jcm93/ares/blob/flatpak/.github/workflows/build-aux.yml

Thanks for reading and apologies if I've missed something obvious.
